cluster.name: ${CLUSTER_NAME}
node.name: ${HOSTNAME}
network.host: 0.0.0.0

path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
bootstrap.memory_lock: true

indices.memory.index_buffer_size: 20%
indices.fielddata.cache.size: 40%
thread_pool.write.queue_size: 1000

xpack.security.enabled: ${XPACK_SECURITY_ENABLED}

cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
