global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sui-indexer'
    environment: 'development'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['sui_elasticsearch:9200']

  - job_name: 'redis'
    static_configs:
      - targets: ['sui_redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['sui_postgres:5432']
